# Generated by Django 3.0.5 on 2020-04-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0002_auto_20200410_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
    ]
