# Generated by Django 3.0.5 on 2020-04-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0003_auto_20200410_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
