# Generated by Django 3.0.5 on 2020-04-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0007_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='picture',
            name='tweet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet_crawl.Tweet'),
        ),
        migrations.AddField(
            model_name='picture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
