# Generated by Django 3.0.5 on 2020-04-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0009_auto_20200428_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='create_datetime',
            field=models.DateTimeField(),
        ),
    ]
