# Generated by Django 3.0.5 on 2020-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_crawl', '0010_auto_20200428_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
